import { arrayToString } from '@/utils/arrayToString';
import {
  INTRO,
  MINIONS_OF_MORDRED_SCRIPT,
  ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
  MERLIN_SCRIPT,
  CLOSING,
  PERCIVAL_SCRIPT,
  PERCIVAL_WITH_MORGANA_SCRIPT,
  MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
  MERLIN_WITH_MORDRED_SCRIPT,
} from './generateNarrationScript.constants';

export const testCases: {
  hasMordred?: boolean;
  hasOberon?: boolean;
  hasPercival?: boolean;
  hasMorgana?: boolean;
  expected: string;
}[] = [
  {
    hasMordred: false,
    hasOberon: false,
    hasPercival: false,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: false,
    hasPercival: false,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: false,
    hasPercival: true,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: false,
    hasPercival: true,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_WITH_MORGANA_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: true,
    hasPercival: false,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: true,
    hasPercival: false,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: true,
    hasPercival: true,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: false,
    hasOberon: true,
    hasPercival: true,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_WITH_MORGANA_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: false,
    hasPercival: false,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: false,
    hasPercival: false,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: false,
    hasPercival: true,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: false,
    hasPercival: true,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_WITH_MORGANA_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: true,
    hasPercival: false,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: true,
    hasPercival: false,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: true,
    hasPercival: true,
    hasMorgana: false,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_SCRIPT,
      CLOSING,
    ]),
  },
  {
    hasMordred: true,
    hasOberon: true,
    hasPercival: true,
    hasMorgana: true,
    expected: arrayToString([
      INTRO,
      MINIONS_OF_MORDRED_WITH_OBERON_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      MERLIN_WITH_MORDRED_SCRIPT,
      ALL_PLAYERS_HANDS_CLOSED_HANDS_FIST,
      PERCIVAL_WITH_MORGANA_SCRIPT,
      CLOSING,
    ]),
  },
];
